# Generated by Django 5.0.2 on 2024-02-16 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qrCodeModel',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'qrcodes',
            },
        ),
        migrations.CreateModel(
            name='QrCodeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodes.qrcodemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qrcodevisit',
                'unique_together': {('user', 'qrcode')},
            },
        ),
    ]
