# Generated by Django 5.0.2 on 2024-02-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_qrcodequestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCodeQuestions',
        ),
    ]
