# Generated by Django 5.0.2 on 2024-02-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0004_qrcodequestions_remove_qrcodemodel_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCodeQuestions',
        ),
    ]
