# Generated by Django 5.0.1 on 2024-03-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0005_delete_qrcodequestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodemodel',
            name='description',
            field=models.TextField(default='new description'),
        ),
        migrations.AddField(
            model_name='qrcodemodel',
            name='name',
            field=models.CharField(default='new bin', max_length=255),
        ),
    ]
