# Generated by Django 5.0.1 on 2024-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0006_qrcodemodel_description_qrcodemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodemodel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=50.735256, max_digits=9),
        ),
        migrations.AlterField(
            model_name='qrcodemodel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-3.533497, max_digits=9),
        ),
    ]
