# Generated by Django 4.1 on 2024-02-27 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0002_useransweredquestion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useransweredquestion",
            unique_together={("question", "user")},
        ),
    ]
