# Generated by Django 5.0.2 on 2024-02-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
