# Generated by Django 5.0.2 on 2024-02-23 19:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinfo_picture_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(default='media/default.png', upload_to=accounts.models.upload__rename),
        ),
    ]
