# Generated by Django 5.0.2 on 2024-02-23 19:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userfriends_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userfriends',
            unique_together={('user_id', 'following')},
        ),
    ]
