# Generated by Django 5.0.2 on 2024-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_userfriends_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfriends',
            name='following',
            field=models.IntegerField(),
        ),
    ]
