# Generated by Django 5.0.2 on 2024-02-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userfriends_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='following',
            new_name='following_id',
        ),
        migrations.AlterUniqueTogether(
            name='userfriends',
            unique_together={('user_id', 'following_id')},
        ),
    ]
