# Generated by Django 5.0.1 on 2024-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_following_userfriends_following_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
