# Generated by Django 5.0.1 on 2024-02-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userinfo_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='score',
            new_name='cumulativeScore',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
