# Generated by Django 5.0.1 on 2024-03-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_score_userinfo_cumulativescore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_name', models.TextField(unique=True)),
                ('background_description', models.TextField()),
                ('picture', models.ImageField(default=None, null=True, upload_to='')),
                ('css_class', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'user_backgrounds',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.TextField(unique=True)),
                ('title_description', models.TextField()),
            ],
            options={
                'db_table': 'user_titles',
            },
        ),
        migrations.CreateModel(
            name='UserOwnedBackgrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.backgrounds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_owned_backgrounds',
                'unique_together': {('user', 'background')},
            },
        ),
        migrations.CreateModel(
            name='UserOwnedTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.titles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_owned_titles',
                'unique_together': {('user', 'title')},
            },
        ),
    ]
