# Generated by Django 5.0.1 on 2024-03-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_backgrounds_titles_userownedbackgrounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.backgrounds'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.titles'),
        ),
    ]
