from quiz.models import *
#Author: Tom
#Populates the question and answer database tables with quiz content.

Question.objects.all().delete()
Answer.objects.all().delete()


q = Question(q_text="What is the current recycle rate of UK households?")
a1 = Answer(question= q, a_text = "74%", correct=False)
a2 = Answer(question= q, a_text = "55%", correct=False)
a3 = Answer(question= q, a_text = "44%", correct=True)
a4 = Answer(question= q, a_text = "31%", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a greenhouse gas?")
a1 = Answer(question= q, a_text = "Oxygen", correct=False)
a2 = Answer(question= q, a_text = "Argon", correct=False)
a3 = Answer(question= q, a_text = "Methane", correct=True)
a4 = Answer(question= q, a_text = "Nitrogen", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following is NOT a renewable energy source?")
a1 = Answer(question= q, a_text = "Hyrdopower", correct=False)
a2 = Answer(question= q, a_text = "Geothermal Energy", correct=False)
a3 = Answer(question= q, a_text = "Solar Power", correct=False)
a4 = Answer(question= q, a_text = "Natural Gas", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following activities is the main contributor to CO2 emissions?")
a1 = Answer(question= q, a_text = "Using plastic bags", correct=False)
a2 = Answer(question= q, a_text = "Driving petrol-powered cars", correct=True)
a3 = Answer(question= q, a_text = "Eating red meat", correct=False)
a4 = Answer(question= q, a_text = "Household appliance usage", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a renewable energy source?")
a1 = Answer(question= q, a_text = "Hydropower", correct=True)
a2 = Answer(question= q, a_text = "Coal", correct=False)
a3 = Answer(question= q, a_text = "Natural Gas", correct=False)
a4 = Answer(question= q, a_text = "Nuclear Power", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What action could you take to REDUCE water pollution?")
a1 = Answer(question= q, a_text = "Go vegan", correct=False)
a2 = Answer(question= q, a_text = "Dump trash in rivers", correct=False)
a3 = Answer(question= q, a_text = "Use reusable water bottles", correct=True)
a4 = Answer(question= q, a_text = "Cause an oil spill", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What impact does climate change have on wildlife?")
a1 = Answer(question= q, a_text = "Increases biodiversity", correct=False)
a2 = Answer(question= q, a_text = "Increases animal population", correct=False)
a3 = Answer(question= q, a_text = "Improves conditions for breeding", correct=False)
a4 = Answer(question= q, a_text = "Destroys natural habitats", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What causes coral reef bleaching?")
a1 = Answer(question= q, a_text = "Rising ocean temperatures", correct=True)
a2 = Answer(question= q, a_text = "Plastic waste in the ocean", correct=False)
a3 = Answer(question= q, a_text = "Overfishing", correct=False)
a4 = Answer(question= q, a_text = "It's a natural process", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which gas is produced by livestock farming?")
a1 = Answer(question= q, a_text = "Carbon Dioxide", correct=False)
a2 = Answer(question= q, a_text = "Carbon Monoxide", correct=False)
a3 = Answer(question= q, a_text = "Methane", correct=True)
a4 = Answer(question= q, a_text = "Nitrogen", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a sustainable lifestyle choice?")
a1 = Answer(question= q, a_text = "Leaving household lights on", correct=False)
a2 = Answer(question= q, a_text = "Using public transportation", correct=True)
a3 = Answer(question= q, a_text = "Taking long showers", correct=False)
a4 = Answer(question= q, a_text = "Driving to work", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()


q = Question(q_text="How can you help to conservere natural resources?")
a1 = Answer(question= q, a_text = "Using single-use plastic products", correct=False)
a2 = Answer(question= q, a_text = "Driving to work", correct=False)
a3 = Answer(question= q, a_text = "Recycling", correct=True)
a4 = Answer(question= q, a_text = "Wasting food", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="how does plastic pollution affect aquatic life?")
a1 = Answer(question= q, a_text = "Causes entanglement and ingestion", correct=True)
a2 = Answer(question= q, a_text = "Improves marine biodiversity", correct=False)
a3 = Answer(question= q, a_text = "Causes the spread of diseases", correct=False)
a4 = Answer(question= q, a_text = "It makes them depressed", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()


q = Question(q_text="Which of the following technologies could help against climate change?")
a1 = Answer(question= q, a_text = "GPS", correct=False)
a2 = Answer(question= q, a_text = "Mobile phones", correct=False)
a3 = Answer(question= q, a_text = "Virtual reality", correct=False)
a4 = Answer(question= q, a_text = "Carbon capture", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()


q = Question(q_text="Which of the following transporation options is the most environmentally friendly?")
a1 = Answer(question= q, a_text = "Driving a gasoline car", correct=False)
a2 = Answer(question= q, a_text = "Walking or biking", correct=True)
a3 = Answer(question= q, a_text = "Taking a bus", correct=False)
a4 = Answer(question= q, a_text = "Riding an electric scooter", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What is the most energy-efficient way to dry clothing?")
a1 = Answer(question= q, a_text = "Using an indoor clothes rack", correct=False)
a2 = Answer(question= q, a_text = "Using a clothes dryer", correct=False)
a3 = Answer(question= q, a_text = "Using a spin dryer", correct=False)
a4 = Answer(question= q, a_text = "Hanging clothes on a clothesline outside", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which energy-efficient technology helps reduce carbon emissions from buildings?")
a1 = Answer(question= q, a_text = "Energy-efficient appliances", correct=True)
a2 = Answer(question= q, a_text = "Single-pane windows", correct=False)
a3 = Answer(question= q, a_text = "Poor insulation", correct=False)
a4 = Answer(question= q, a_text = "Incandescent light bulbs", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following contributes most to reducing carbon emissions?")
a1 = Answer(question= q, a_text = "Eating a plant-based diet", correct=True)
a2 = Answer(question= q, a_text = "Driving an electric car", correct=False)
a3 = Answer(question= q, a_text = "Installing solar panels on your roof", correct=False)
a4 = Answer(question= q, a_text = "Turning off lights when not in use", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What is the most effective way to conserve water at home?")
a1 = Answer(question= q, a_text = "Taking shorter showers", correct=False)
a2 = Answer(question= q, a_text = "Using a low-flow toilet", correct=True)
a3 = Answer(question= q, a_text = "Watering plants with collected rainwater", correct=False)
a4 = Answer(question= q, a_text = "Fixing leaky faucets", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following household activities typically consumes the most water?")
a1 = Answer(question= q, a_text = "Doing laundry", correct=False)
a2 = Answer(question= q, a_text = "Watering the garden", correct=False)
a3 = Answer(question= q, a_text = "Washing dishes by hand", correct=False)
a4 = Answer(question= q, a_text = "Taking a shower", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What is a sustainable alternative to driving alone to work?")
a1 = Answer(question= q, a_text = "Carpooling", correct=True)
a2 = Answer(question= q, a_text = "Taking a helicopter", correct=False)
a3 = Answer(question= q, a_text = "Getting an uber", correct=False)
a4 = Answer(question= q, a_text = "Taking a private jet", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="How can you effectivley reduce food waste at home?")
a1 = Answer(question= q, a_text = "Buying food in bulk", correct=False)
a2 = Answer(question= q, a_text = "Throwing away leftovers", correct=False)
a3 = Answer(question= q, a_text = "Planning meals and meal prepping", correct=True)
a4 = Answer(question= q, a_text = "Storing food in single-use containers", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()