from quiz.models import *

q = Question(q_text="What is the current recycle rate of UK households?")
a1 = Answer(question= q, a_text = "74%", label="x", correct=False)
a2 = Answer(question= q, a_text = "55%", label="x", correct=False)
a3 = Answer(question= q, a_text = "44%", label="x", correct=True)
a4 = Answer(question= q, a_text = "31%", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a greenhouse gas?")
a1 = Answer(question= q, a_text = "Oxygen", label="x", correct=False)
a2 = Answer(question= q, a_text = "Argon", label="x", correct=False)
a3 = Answer(question= q, a_text = "Methane", label="x", correct=True)
a4 = Answer(question= q, a_text = "Nitrogen", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following is NOT a renewable energy source?")
a1 = Answer(question= q, a_text = "Hyrdopower", label="x", correct=False)
a2 = Answer(question= q, a_text = "Geothermal Energy", label="x", correct=False)
a3 = Answer(question= q, a_text = "Solar Power", label="x", correct=False)
a4 = Answer(question= q, a_text = "Natural Gas", label="x", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following activities is the main contributor to CO2 emissions?")
a1 = Answer(question= q, a_text = "Using plastic bags", label="x", correct=False)
a2 = Answer(question= q, a_text = "Driving petrol-powered cars", label="x", correct=True)
a3 = Answer(question= q, a_text = "Eating red meat", label="x", correct=False)
a4 = Answer(question= q, a_text = "Household appliance usage", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a renewable energy source?")
a1 = Answer(question= q, a_text = "Hydropower", label="x", correct=True)
a2 = Answer(question= q, a_text = "Coal", label="x", correct=False)
a3 = Answer(question= q, a_text = "Natural Gas", label="x", correct=False)
a4 = Answer(question= q, a_text = "Nuclear Power", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What action could you take to REDUCE water pollution?")
a1 = Answer(question= q, a_text = "Go vegan", label="x", correct=False)
a2 = Answer(question= q, a_text = "Dump trash in rivers", label="x", correct=False)
a3 = Answer(question= q, a_text = "Use reusable water bottles", label="x", correct=True)
a4 = Answer(question= q, a_text = "Cause an oil spill", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What impact does climate change have on wildlife?")
a1 = Answer(question= q, a_text = "Increases biodiversity", label="x", correct=False)
a2 = Answer(question= q, a_text = "Increases animal population", label="x", correct=False)
a3 = Answer(question= q, a_text = "Improves conditions for breeding", label="x", correct=False)
a4 = Answer(question= q, a_text = "Destroys natural habitats", label="x", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="What causes coral reef bleaching?")
a1 = Answer(question= q, a_text = "Rising ocean temperatures", label="x", correct=True)
a2 = Answer(question= q, a_text = "Plastic waste in the ocean", label="x", correct=False)
a3 = Answer(question= q, a_text = "Overfishing", label="x", correct=False)
a4 = Answer(question= q, a_text = "It's a natural process", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which gas is produced by livestock farming?")
a1 = Answer(question= q, a_text = "Carbon Dioxide", label="x", correct=False)
a2 = Answer(question= q, a_text = "Carbon Monoxide", label="x", correct=False)
a3 = Answer(question= q, a_text = "Methane", label="x", correct=True)
a4 = Answer(question= q, a_text = "Nitrogen", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a sustainable lifestyle choice?")
a1 = Answer(question= q, a_text = "Leaving household lights on", label="x", correct=False)
a2 = Answer(question= q, a_text = "Using public transportation", label="x", correct=True)
a3 = Answer(question= q, a_text = "Taking long showers", label="x", correct=False)
a4 = Answer(question= q, a_text = "Driving to work", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()


q = Question(q_text="How can you help to conservere natural resources?")
a1 = Answer(question= q, a_text = "Using single-use plastic products", label="x", correct=False)
a2 = Answer(question= q, a_text = "Driving to work", label="x", correct=False)
a3 = Answer(question= q, a_text = "Recycling", label="x", correct=True)
a4 = Answer(question= q, a_text = "Wasting food", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="how does plastic pollution affect aquatic life?")
a1 = Answer(question= q, a_text = "Causes entanglement and ingestion", label="x", correct=True)
a2 = Answer(question= q, a_text = "Improves marine biodiversity", label="x", correct=False)
a3 = Answer(question= q, a_text = "Causes the spread of diseases", label="x", correct=False)
a4 = Answer(question= q, a_text = "It makes them depressed", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following IS a renewable energy source?")
a1 = Answer(question= q, a_text = "Hydropower", label="x", correct=True)
a2 = Answer(question= q, a_text = "Coal", label="x", correct=False)
a3 = Answer(question= q, a_text = "Natural Gas", label="x", correct=False)
a4 = Answer(question= q, a_text = "Nuclear Power", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which of the following technologies could help against climate change?")
a1 = Answer(question= q, a_text = "GPS", label="x", correct=False)
a2 = Answer(question= q, a_text = "Mobile phones", label="x", correct=False)
a3 = Answer(question= q, a_text = "Virtual reality", label="x", correct=False)
a4 = Answer(question= q, a_text = "Carbon capture", label="x", correct=True)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()

q = Question(q_text="Which energy-efficient technology helps reduce carbon emissions from buildings?")
a1 = Answer(question= q, a_text = "Energy-efficient appliances", label="x", correct=True)
a2 = Answer(question= q, a_text = "Single-pane windows", label="x", correct=False)
a3 = Answer(question= q, a_text = "Poor insulation", label="x", correct=False)
a4 = Answer(question= q, a_text = "Incandescent light bulbs", label="x", correct=False)
q.save()
a1.save()
a2.save()
a3.save()
a4.save()